# Generated by Django 2.1.1 on 2019-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190126_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='other_authors',
            field=models.CharField(blank=True, default='None', max_length=300, null=True),
        ),
    ]
